version: '3'

services:
  job-portal:
    container_name: job-portal
    image: job-portal
    ports:
      - "8080:8080"
    build: .
    env_file:
      - .env
      - .db.env
      - .app.redis.env
      - .keys.env
    depends_on:
      - postgres
      - redis
    restart: always
  
  postgres:
    container_name: postgres
    image: postgres
    ports:
     - "5432:5432"
    env_file:
      - .appdb.env
  
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .redis.env
    restart : always

    