version: '3'

services:
  job-portal:
    container_name: job-portal
    image: job-portal
    ports:
      - "8080:8080"
    build: .
  
  postgres:
    container_name: postgres
    image: postgres
    ports:
     - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=job-portal-api
  

    